# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e19986ddb103da8f5dd73ece9a66baebedbb62cf271b45489e886cf7c82d73378266b8ef0e525809c4391a443b33add2f2b0895e8b950e35445697adc86347fc

test:
  secret_key_base: 5f57e521b58a60bf2e8c08f8ebf2d98d072d67c5d4d9eb2ca9cbf7b6d5c536c2ae12f54f60425e1dbffb1966fad57d8ceff64196a3c3958d6eaa98fcb3dc22d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
